### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'vscode/extensions/ms-python'

### ISSUE THREAD

**Issue by paultipper** [bulletmark/debugpy-run#6]
I've installed debugpy-run, and am trying to debug a package.py script within my terraform by kicking off a `terraform plan` command via a `make` command. When I try this, I get the following error:

```
10:36 $ debugpy-run make apply-local
Traceback (most recent call last):
  File "/Users/ac8dqzz/opt/anaconda3/bin/debugpy-run", line 8, in <module>
    sys.exit(main())
  File "/Users/ac8dqzz/opt/anaconda3/lib/python3.8/site-packages/debugpy_run.py", line 89, in main
    cmd = None if args.global_only else find_ext_debugger()
  File "/Users/ac8dqzz/opt/anaconda3/lib/python3.8/site-packages/debugpy_run.py", line 35, in find_ext_debugger
    extdir = sorted(pdirs, reverse=True, key=sortdir)[0]
  File "/Users/ac8dqzz/opt/anaconda3/lib/python3.8/site-packages/debugpy_run.py", line 33, in sortdir
    return f'{v[0]}.{int(v[1]):02}.{v[2]}'
ValueError: invalid literal for int() with base 10: 'vscode/extensions/ms-python'
```

My remote launch configuration is as follows:

```json
{
            "name": "Python: Attach to debugpy-run",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ],
            "justMyCode": true
        }
```

Am I doing something wrong here, or is this a bug?

**Comment by bulletmark** [comment]
`debugpy` (and `debugpy-run`) are intended to run and debug Python programs. Unless I am completely missing something, you are trying to use it to run and debug `make` which is a compiled C program. That is never going to work!

**Comment by paultipper** [comment]
OK, I understand. The script I'm actually trying to run is `tflocal`, which is a Python script designed to be run from the command line (hence the lack of a .py extension), so I tried the following:

```bash
debugpy-run tflocal apply
```
but I still get exactly the same error:

```bash
12:33 $ debugpy-run tflocal apply
Traceback (most recent call last):
  File "/Users/ac8dqzz/opt/anaconda3/bin/debugpy-run", line 8, in <module>
    sys.exit(main())
  File "/Users/ac8dqzz/opt/anaconda3/lib/python3.8/site-packages/debugpy_run.py", line 89, in main
    cmd = None if args.global_only else find_ext_debugger()
  File "/Users/ac8dqzz/opt/anaconda3/lib/python3.8/site-packages/debugpy_run.py", line 35, in find_ext_debugger
    extdir = sorted(pdirs, reverse=True, key=sortdir)[0]
  File "/Users/ac8dqzz/opt/anaconda3/lib/python3.8/site-packages/debugpy_run.py", line 33, in sortdir
    return f'{v[0]}.{int(v[1]):02}.{v[2]}'
ValueError: invalid literal for int() with base 10: 'vscode/extensions/ms-python'
```
I typed the following to verify that `tflocal` is a Python executable:
```bash
12:33 $ which tflocal
/Users/ac8dqzz/opt/anaconda3/bin/tflocal
(venv) (base) ✔ ~/Documents/Development/DSC/spinning-jenny/spinningjenny-backend/infrastructure [tf-atlantis|✚ 7…4⚑ 1] 
12:34 $ file /Users/ac8dqzz/opt/anaconda3/bin/tflocal
/Users/ac8dqzz/opt/anaconda3/bin/tflocal: a /Users/ac8dqzz/opt/anaconda3/bin/python script text executable, ASCII text
```
Is it because the tflocal doesn't have the .py extension that this error is being produced?

**Comment by bulletmark** [comment]
No, certainly do not need `.py` extension. Where does `tflocal` come from? Is it something you created yourself? Prove it can run directly on the command line. Also prove you can run it natively with `debugpy`.

I see you are using Conda which I have no experience with. There is a possibility that I make assumptions about directories etc which are not appropriate to Conda. What is the output of `ls -ld ~/.vscode`?

**Comment by paultipper** [comment]
`tflocal` is a thin python wrapper around the `terrraform` CLI, written by [LocalStack](https://localstack.cloud/) to allow resources to be deployed to a LocalStack instance using terraform. It is a python script that can be executed as a CLI command by way of a shebang line, i.e.:

```bash
#!/Users/ac8dqzz/opt/anaconda3/bin/python
```
 I've run it many times from the command line successfully, although I've never tried it with debugpy - I'll try that shortly.

If I type `ls -ld .vscode` from the `./infrastructure` directory from which the `tflocal` command is issued, I get:

```bash
14:08 $ ls -ld .vscode
ls: .vscode: No such file or directory
```

which is not surprising, as my .vscode directory is one level up.

**Comment by bulletmark** [comment]
Please type that command exactly as I wrote it.

**Comment by bulletmark** [comment]
Also, still not clear to me if you created that `tflocal` script or not? Sure the `terraform` CLI is written by LocalStack but your sentence is ambiguous if they also provide `tflocal`. Clearly LocalStack do not  write a script with your name in the shebang. Does `tflocal` get created in some way?

**Comment by paultipper** [comment]
> Also, still not clear to me if you created that `tflocal` script or not? Sure the `terraform` CLI is written by LocalStack but your sentence is ambiguous if they also provide `tflocal`. Clearly LocalStack do not write a script with your name in the shebang. Does `tflocal` get created in some way?

I definitely didn't create the `tflocal` script. I assume the shebang statement was generated when I installed `tflocal` using the `pip install terraform-local` command (see https://docs.localstack.cloud/integrations/terraform/#using-the-tflocal-script).

**Comment by paultipper** [comment]
> Please type that command exactly as I wrote it.

Apologies - I misread what you wrote. I'll try it again with the correct command.

**Comment by paultipper** [comment]
> ls -ld ~/.vscode

```
11:56 $ ls -ld ~/.vscode
drwxr-xr-x  4 ac8dqzz  MMM\Domain Users  128 14 Oct  2021 /Users/ac8dqzz/.vscode
```

**Comment by bulletmark** [comment]
Can you please provide the output of the command `find ~/.vscode -iname debugpy`.

Still not sure what you are trying to do though. So you are opening the `/Users/ac8dqzz/opt/anaconda3/bin/tflocal` source file in VS Code and then you want to run and debug that?

**Comment by bulletmark** [comment]
Closing because no response from OP.

**Comment by krazyito65** [comment]
I have this same exact issue.
```
$ find ~/.vscode -iname debugpy
/Users/leon.solis/.vscode/extensions/ms-python.python-2022.16.0/pythonFiles/lib/python/debugpy
/Users/leon.solis/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy
```

my set up:  I'm on a macbook provided by my company.  I use to have it working previously, but i had to re-image my macbook due to some company issue.  When I tried to reinstall it i get this error, even when running without a python file.

**Comment by krazyito65** [comment]
just to be clear:  this was working for me 1 week ago, well after this post was created, but now when i reinstall it on a new install of this macbook, it gave this error.

**Comment by bulletmark** [comment]
The OP above reports an error when he runs `debugpy-run`. You say you get when you "try to reinstall it" so it seems you have a completely different problem. Please paste the exact output of the command you run with the error you get.

**Comment by krazyito65** [comment]
Sorry i misspoke, i was just iterating that i reinstalled it recently.  The error happens when I run the executable.

```
(dlci_py3_venv) [19:51:11]-[leon.solis@CQL474WXMX git_repos]$ debugpy-run
Traceback (most recent call last):
  File "/Users/leon.solis/bin/debugpy-run", line 8, in <module>
    sys.exit(main())
  File "/Users/leon.solis/Library/Python/3.9/lib/python/site-packages/debugpy_run.py", line 89, in main
    cmd = None if args.global_only else find_ext_debugger()
  File "/Users/leon.solis/Library/Python/3.9/lib/python/site-packages/debugpy_run.py", line 35, in find_ext_debugger
    extdir = sorted(pdirs, reverse=True, key=sortdir)[0]
  File "/Users/leon.solis/Library/Python/3.9/lib/python/site-packages/debugpy_run.py", line 33, in sortdir
    return f'{v[0]}.{int(v[1]):02}.{v[2]}'
ValueError: invalid literal for int() with base 10: 'vscode/extensions/ms-python'```

**Comment by krazyito65** [comment]
```[19:59:28]-[leon.solis@CQL474WXMX launch-ci] [zshield|✔]$ debugpy-run launch.py
Traceback (most recent call last):
  File "/Users/leon.solis/bin/debugpy-run", line 8, in <module>
    sys.exit(main())
  File "/Users/leon.solis/Library/Python/3.9/lib/python/site-packages/debugpy_run.py", line 89, in main
    cmd = None if args.global_only else find_ext_debugger()
  File "/Users/leon.solis/Library/Python/3.9/lib/python/site-packages/debugpy_run.py", line 35, in find_ext_debugger
    extdir = sorted(pdirs, reverse=True, key=sortdir)[0]
  File "/Users/leon.solis/Library/Python/3.9/lib/python/site-packages/debugpy_run.py", line 33, in sortdir
    return f'{v[0]}.{int(v[1]):02}.{v[2]}'
ValueError: invalid literal for int() with base 10: 'vscode/extensions/ms-python'```

launch.py is a file that my team created, it is a custom python package we use for our CI/CD pipeline.  I've previously gotten it to work prior wiping my machine

**Comment by bulletmark** [comment]
I just pushed a new version to main branch. Can you please try that?

**Comment by krazyito65** [comment]
So that seems to have worked for me. Thanks!

To be fully transparent here is my log of what I did.
```sh
[01:59:08]-[leon.solis@CQL474WXMX debugpy-run] [main|✔]$ git pull 
warning: redirecting to https://github.com/bulletmark/debugpy-run/
Updating 3860223..3c54ba6
Fast-forward
 README.md      |  9 +++++----
 debugpy_run.py | 12 ++++++++----
 setup.py       |  3 ++-
 3 files changed, 15 insertions(+), 9 deletions(-)
[01:59:10]-[leon.solis@CQL474WXMX debugpy-run] [main|✔]$ git pull
warning: redirecting to https://github.com/bulletmark/debugpy-run/
Already up to date.
[01:59:12]-[leon.solis@CQL474WXMX debugpy-run] [main|✔]$ pip3 install -U .
Defaulting to user installation because normal site-packages is not writeable
Processing /Users/leon.solis/git_repos/debugpy-run
  Preparing metadata (setup.py) ... done
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 977.0 kB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 2.2 MB/s eta 0:00:00
Building wheels for collected packages: debugpy-run
  Building wheel for debugpy-run (setup.py) ... done
  Created wheel for debugpy-run: filename=debugpy_run-1.5.1-py3-none-any.whl size=10204 sha256=ee39028ef449a4ff2c238dc4e12281f7d313c6757c20ac8d19bc83f43da965ef
  Stored in directory: /Users/leon.solis/Library/Caches/pip/wheels/42/4c/06/aa98b08f25720d0359725e8ad9df73cfe3322261a9b98ba76a
Successfully built debugpy-run
Installing collected packages: pyparsing, packaging, debugpy-run
  Attempting uninstall: debugpy-run
    Found existing installation: debugpy-run 1.5
    Uninstalling debugpy-run-1.5:
      Successfully uninstalled debugpy-run-1.5
  WARNING: The script debugpy-run is installed in '/Users/leon.solis/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed debugpy-run-1.5.1 packaging-21.3 pyparsing-3.0.9
[01:59:31]-[leon.solis@CQL474WXMX debugpy-run] [main|✔]$ /Users/leon.solis/Library/Python/3.9/bin/debugpy-run 
usage: debugpy-run [-h] [--listen] [-W] [-C] [-p PORT] [-g] [-r] [--log-to PATH | --log-to-stderr] [-m MODULE | -c CODE | --pid PID | -V] [program] ...
debugpy-run: error: Must specify program, module, code, or pid.
[01:59:43]-[leon.solis@CQL474WXMX debugpy-run] [main|✔]$ debugpy-run 
usage: debugpy-run [-h] [--listen] [-W] [-C] [-p PORT] [-g] [-r] [--log-to PATH | --log-to-stderr] [-m MODULE | -c CODE | --pid PID | -V] [program] ...
debugpy-run: error: Must specify program, module, code, or pid.
[01:59:51]-[leon.solis@CQL474WXMX debugpy-run] [main|✔]$ which debugpy-run
/Users/leon.solis/bin/debugpy-run
[02:00:00]-[leon.solis@CQL474WXMX debugpy-run] [main|✔]$ debugpy-run --version
/Users/leon.solis/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy 1.6.3
[02:00:12]-[leon.solis@CQL474WXMX debugpy-run] [main|✔]$ /Users/leon.solis/Library/Python/3.9/bin/debugpy-run --version
/Users/leon.solis/.vscode/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy 1.6.3
[02:00:56]-[leon.solis@CQL474WXMX debugpy-run] [main|✔]$ pip3 show debugpy-run
Name: debugpy-run
Version: 1.5.1
Summary: Finds and runs debugpy for VS Code "remote attach" command line debugging.
Home-page: https://github.com/bulletmark/debugpy-run
Author: Mark Blakeney
Author-email: mark.blakeney@bullet-systems.net
License: GPLv3
Location: /Users/leon.solis/Library/Python/3.9/lib/python/site-packages
Requires: packaging
Required-by: 
[02:01:01]-[leon.solis@CQL474WXMX debugpy-run] [main|✔]$ pwd
/Users/leon.solis/git_repos/debugpy-run
[02:04:29]-[O778195@CQL474WXMX debugpy-run] [main|✔]$ cd ../launch-ci/
[02:04:32]-[O778195@CQL474WXMX launch-ci] [develop|✔]$ debugpy-run launch.py 
Running debugpy --listen 5678 --wait-for-client launch.py
```

**Comment by bulletmark** [comment]
Fixed and released as new version 1.6.
